sudo: required

env:
  matrix:
    - DISTRIBUTION: centos
      VERSION: 7
    - DISTRIBUTION: ubuntu
      VERSION: 16.04

services:
  - docker

before_install:
    # Install latest Git
  - sudo apt-get update
  - sudo apt-get install --only-upgrade git
    # Allow fetching other branches than master
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
    # Fetch the branch with test code
  - git fetch origin docker-tests
  - git worktree add tests origin/docker-tests

script:
  # Running the test script the first time will set up the master DNS server
  # with IP 172.17.0.2. Running it the second time sets up the slave DNS
  # server with IP 172.17.0.3.
  - ./tests/docker-tests.sh
  - ./tests/docker-tests.sh

  # Run functional tests on both master and slave server
  - SUT_IP=172.17.0.2 ./tests/functional-tests.sh
  # Ensure the slave gets the chance to receive zone updates from the master
  - sleep 6s
  - SUT_IP=172.17.0.3 ./tests/functional-tests.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
