# roles/bind/handlers/main.yml
---

- name: restart bind
  service:
    name: "{{ bind_service }}"
    state: restarted

- name: restart network
  service:
    name: network
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: true
