---
name: onebula
domain: srt.basealt.ru
nodes:
  ones: &onef
    type: pve
    arch: "x86_64"
    count: 1
    cpus: 1
    cores: 1
    mem: 1024
    template: alt-server-sisyphus-x64-20190525
    net:
      eth0: &eth0
        bridge: "vmbr1"
        tag: 994
        descr: pub
        ipv4:
        - "10.64.84.240/24"
        default: "10.64.84.1"
        nameservers:
        - "8.8.8.8"

  onew:
    <<: *onef
    mem: 4096
    count: 3
    net:
      eth0:
        <<: *eth0
        ipv4:
        - "10.64.84.246/24"
      eth1: &eth1
        bridge: "vmbr1"
        tag: 948
        descr: ovs-integration
        ipv4:
        - "10.64.7.250/24"

