---
name: demo-samba-3x3-sisyphus
domain: demo.alt
nodes:
  dc:
    type: pve
    arch: "x86_64"
    count: 3
    cpus: 1
    cores: 2
    mem: 1024
    template: alt-server-sisyphus-x64-20181106
    net:
      eth0:
        bridge: "vmbr1"
        tag: 962
        descr: pub
        ipv4:
        - "10.64.62.10/24"
        default: "10.64.62.1"
        nameservers:
        - "8.8.8.8"
      eth1:
        bridge: "vmbr1"
        tag: 942
        descr: priv
        ipv4:
        - "10.64.6.1/24"
        search:
        - "demo.alt"
  clw:
    type: pve
    arch: "x86_64"
    count: 3
    cpus: 1
    cores: 2
    mem: 1024
    template: alt-kworkstation-sisyphus-x64-20181106
    net:
      eth0:
        bridge: "vmbr1"
        tag: 962
        descr: pub
        ipv4:
        - "10.64.62.100/24"
        default: "10.64.62.1"
        nameservers:
        - "8.8.8.8"
      eth1:
        bridge: "vmbr1"
        tag: 942
        descr: priv
        ipv4:
        - "10.64.6.100/24"
        nameservers:
        - "10.64.6.1"
        search:
        - "demo.alt"
