---
name: remote-template
domain: domain.alt
nodes:
  rs:
    type: pve
    arch: "x86_64"
    platform: "p8"
    count: 2
    cpus: 1
    cores: 2
    mem: 1024
    template: alt-workstation-82-x64
    net:
      eth0:
        bridge: "vmbr1"
        tag: 10
        descr: pub
        ipv4:
        - "10.64.0.90/24"
        default: "10.64.0.1"
        nameservers:
        - "8.8.8.8"
      eth1:
        bridge: "vmbr1"
        tag: 911
        descr: priv
        ipv4:
        - "10.64.6.200/24"
        nameservers:
        - "10.64.6.1"
        search:
        - "domain.alt"
