---
apt:
  sources:
    local:
      enabled: yes
      url: "http://10.64.0.6/"

pve:
  api_url: "10.64.0.6"
  username: "prod@pve"
  password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;prod
          37363439386464653161343832313634643766323630383065363532333435323136663064303661
          3437366635363430623664303537613936336663383331320a636232373463383366393037653963
          36353337333063383131616237326365386363613564373836633363626237313138636464323566
          3365653037376230380a393635336337626637653664623765326435323530326130306136333138
          37663062613261343164663861613734353463393530353133306561363034663239
  storage: datastore

lxc:
  e2k:
    arch: "e2k"
    hostname: "e2k"
    username: "root"
  baikal:
    arch: "mips"
    hostname: "baikal"
    username: "root"
  tavolga:
    arch: "mips"
    hostname: "tavolga"
    username: "root"

users:
  robot:
    ssh-key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOJSeRmDdbpn7axn0gJRRxmKXOygmpuR56Y3mP89nyIf robot@smb.basealt.ru"

  omg:
    ssh-key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICrTiVrnp5ZxMSM9ZFGSuGa32KMBLBiPcy13Q+KEs5SL omg@altlinux.org"
    pgp-key: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----

      mDMEWomDvhYJKwYBBAHaRw8BAQdAsdDc8Q7lXEyJQOYz+D1Fz6tIY13UCTNO8nTu
      V+xXsZy0HlNlcmdleSBCdWJub3YgPG9tZ0BiYXNlYWx0LnJ1PoiQBBMWCAA4FiEE
      3cRKTI/AHDyVG7uq0OqbT7nk5AQFAlq87hICGwMFCwkIBwMFFQoJCAsFFgIDAQAC
      HgECF4AACgkQ0OqbT7nk5ARdDQEAok31M9v54CUKrf9b3kbZSqGVw9C0WBvpXIxq
      Np3X8pIA/1ktZme5uHKELdIigncnffJ6O01q2OeGKakgdtV8R9cPiQIzBBABCAAd
      FiEEy5HhrGjjiXXhcfxfxhe5ZCHl2FsFAlrq6oUACgkQxhe5ZCHl2FvfpQ/+MxAX
      lgHT/tkWg9eHAWFsqEEZNgzdlQfE6Tvix9uprcK16kHHTdp/SGwETqyrB+mUP0Rp
      Gxyhgf0LQ2Y2rSFbJYADnfuVqVQ9KdwyD3mYIVMTwPSWv1VXNs8o67/ZZxn84Kxo
      RiYHfrQUlricoGyH3fHZTV3NAIl8kE5WBZhO5uzBKKDIiIZ3gCBQr0b8mRKNIWRZ
      F9Ery1RfzEwWnWQanNHaiRX5lMmRrRTnwklBI/K6rTQNgDv3N85kCZngex1UjZRx
      sQwpOUkANFCn3EpKS2sskvgVFb+nIVp5OARsV6+rEzJIUFoe0zoq5vqpGvELXWVg
      EVMreLykdNeLAqagyL1cgZpHh0JLZcb6iRCRgl23aos41T/iGR3VyJpfYaJ99E+N
      hyJVwu4Ji/6MkQ8bC0F8xIBZAAH7pqt3IGfTxXFY4ML8HUYVCmHBjyI2/TZr0Qk4
      K5mSkZgb+6akFz/O2lCjWnw0l2Lnh/tA7dXLqYwXEj7UUGHAG/hiT9mNQqS6aisz
      V2okWIAbGAvibJa0ZIzQ3AXiVQRgyyYha7kH+OYDQCthC0f8oLJaLH662SHebN/5
      +SiErWcf340rCtwxlPXH7gQtRylZUSMTuJgYxBist3OP9IxrtQVnS8DRJWXaUtb/
      tHbWBb6NZ8sFHuZT+Dw/XtwhOIcFAtXt/lU/m5S0NVNlcmdleSBCdWJub3YgKHBh
      c3MgZW5jcnlwdGlvbikgPG9tZ2JlYmViZUBnbWFpbC5jb20+iJAEExYIADgWIQTd
      xEpMj8AcPJUbu6rQ6ptPueTkBAUCWomDvgIbAwULCQgHAwUVCgkICwUWAgMBAAIe
      AQIXgAAKCRDQ6ptPueTkBKk0APwMRwBfRyLV5uSPXfumWlqIUTmtQYuK9V6Jbprt
      Q91N5gEAz5FeJ5XJzq/LsjRgs0SsEMKYnEfW+7S0eEhpLUyY9gOJAjMEEAEIAB0W
      IQTLkeGsaOOJdeFx/F/GF7lkIeXYWwUCWurqhwAKCRDGF7lkIeXYW5yLEACetHXz
      7n5hFUA9+zu0m+feZfiaUYhfxnePq+HMxvNjrrtYOWABLayuVUTW7TdhQWUEuZKl
      8874ueeGBIe2vQ2IgU8Qg6lA1nu1bdkwYlaOHq+6LWDuCudao5mdrVC44UuIeo6q
      Bjj8jg3PofJsvvEBtNZRst36jhNiboj4dBHGYGQd8145KtX1/ccO6zArT1F1Lo0L
      rSMvncVXwO5qwPUCtnz/MW2t7+kWnSAMghFAh1lUZKC4KQAYM1KufNjtx36KzeQH
      4xrE4QYTWR/0/LtQfgM6YWA3DOdL0j4d68zApfxoP/DI2L//cBOu8Umh2AyX2tZn
      7nEkuRzfGFhuuRLwJqkB9SuCEMtNXFMdF+s4SQ6yyGZ7FRVKtF83Zh5uEpQ1cQBJ
      0GDX3xfocksYHXOSS4uEwyFgBl6Y8sGZLlS15r9xgdd//lfzcfkcKGQePIomsMmV
      a0SMhJwKCPfooKI4aKDC7oLFGz7NfqXLrrNpRvApkdv68vtOh+XWgxIKzOmIHnXz
      6sWgj3piBa7GKg283Bvaus9uM/4+VirGZFa+4rm6hT1LmyolpiuVw2NS8a/+LDHu
      UavBm0WtZ5DO70xaTXqPdT3o2lr6fhVGnK9C1ghTk3j3s8nICap2XwTBNwMfw5/e
      qdmdeSPEUglplE29fyUR7uDpjO3iLz8QQI0Aybg4BFqJg74SCisGAQQBl1UBBQEB
      B0DjdcGryjSgOnfcyZkUkVy4aj85mjlSJybuVnHfxZWyEQMBCAeIeAQYFggAIBYh
      BN3ESkyPwBw8lRu7qtDqm0+55OQEBQJaiYO+AhsMAAoJENDqm0+55OQE78oBAIt+
      OWMke2Mx2HDbsYZudfluyHie9O3DBGfgZOorA4EIAQCTBtmxFYAi9aijm6y8qoAA
      S9JL634Y6tN6se64BDziA7g4BFq85EYSCisGAQQBl1UBBQEBB0B/jnA2GZoiv+zh
      LhfEx8eH7RAqpcFYoziI9Krb36tEbgMBCAeIeAQYFggAIBYhBN3ESkyPwBw8lRu7
      qtDqm0+55OQEBQJavORGAhsMAAoJENDqm0+55OQE88sBAM1v6gjwHDaxkxLcHUil
      m9vPWDtuFV17pwq43SX6lxjzAQD7k85zwTNSP5RM0Sw+u2CG//fkYo/DczHF0GoZ
      8dm+CrgzBFq87sUWCSsGAQQB2kcPAQEHQKH51gRzJFqs6AVBchmHy5p7kmMUOZwS
      K/xWfXeneCEPiO8EGBYIACAWIQTdxEpMj8AcPJUbu6rQ6ptPueTkBAUCWrzuxQIb
      IgCBCRDQ6ptPueTkBHYgBBkWCAAdFiEEsg3o3fBJa4/ilko5mDTkhlOXb+YFAlq8
      7sUACgkQmDTkhlOXb+beNwD/U5TDvOIdzHRisXqB3HtiO5MqMt8brbw3dQx9gpRz
      198A/02cmJFNmAZ+FLyz6L2szgHYFutwyK3tx2Oo0MMqybgKfbUBALKYzYIpa+9G
      701lIfsCtRriAalJNa9Xmp5+lggRw07xAP9339sXSNj3QnQhWbX3++LbnG2aMH8V
      f0rr6pTfx6MUDQ==
      =ty0f
      -----END PGP PUBLIC KEY BLOCK-----

  sin:
    ssh-key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC0y2/XGmnLIN9K3qES2+yES3UkyX5iQhSFr3tyyIwT4 sin@altlinux.org"
    pgp-key: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----

      mQGiBD+0wzcRBACxCuvOYERp4wAXu6+BsIC59H+v3kNLWXSIYKeO3Inu9ZzkAXf+
      8fHXNko7RHK03ZMMo4frvUADDNh0kcxCLev2H+FvdoLpjxicMeeDfGabPdjZ7pgB
      ybEQ0wsBChL2LfP1uUe2QowDoL3DF4sl+uc7r8kVBHWzUn7ncj+lw6pfWwCg8tMp
      qfLodmlAFImHYdewQxrViKcD/Ro7mtqToWim2sgHoURQqjC3jdURJI6qSRNsNwDo
      7nER4CHl8lHEiIEDCEYKsGuTUwFGRUuKuazioka7SBTE393RfyiSHmMEM3MkLA8M
      7UkvfRyC8vGoqXwLPZfSsnYACrzB6Ju4MqXIBGtU0CQZLt3XkLjiog6lZPNAmMOA
      MW6SBACmG1IbwAdGZlDnRCcErCJILIgMLA9uMcSMfm7oyg3M6ruJRUavVdZ80Kwe
      T7V/RrmNNruaXkf22KmDtpGZBfWYXaKWaKE/f/n3UcBCU0ShXSHcKKoRcgmZjd78
      UpYTAO5IqIOLXjbDvjFD3q3SrQFPAwtpPMAHD0JGgf1enNzHY7QoRXZnZW55IFNp
      bmVsbmlrb3YgPGdtYXN0ZXJzaW5AZ21haWwuY29tPohiBBMRAgAiBQJZpjyxAhsD
      BgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRAcL8A7qSHaytHOAKCA7yaYYDiq
      YQncMjFCMwwdPnbF+ACfTpc9Js4GwpKk6WTHtPfkWg2niPa0LkV2Z2VueSBTaW5l
      bG5pa292IChFdGVyc29mdCkgPHNpbkBldGVyc29mdC5ydT6IYgQTEQIAIgUCTgld
      WAIbAwYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQHC/AO6kh2sq0cACfdgcQ
      +/oofweipcqs1Hvh1zIOsjgAoJkB8W044EIj2GaMt5q4FHA5LxvttClFdmdlbnkg
      U2luZWxuaWtvdiAoU2luKSA8c2luQGFsdGxpbnV4LnJ1PoheBBMRAgAeBQI/tMM3
      AhsDBgsJCAcDAgMVAgMDFgIBAh4BAheAAAoJEBwvwDupIdrKLzkAniyGt3Q4uPZq
      +Bqh47OKwpWtL94tAKDi0AQuxNrdY83PQNjuBZ8euCNuBoheBBMRAgAeBQI/tMM3
      AhsDBgsJCAcDAgMVAgMDFgIBAh4BAheAAAoJEBwvwDupIdrKLzkAoO6fswGO1ycX
      rJJ8eaO+SpvQ//PlAKCemIqgFJsdJQsODWLfySLmLmM2E7QqRXZnZW55IFNpbmVs
      bmlrb3YgKEFMVCkgPHNpbkBhbHRsaW51eC5vcmc+iGUEExECACUCGwMGCwkIBwMC
      BhUIAgkKCwQWAgMBAh4BAheABQJaVjg1AhkBAAoJEBwvwDupIdrKaLYAoIEBgL6e
      w4QuvrL6EYLuyWGRJCzAAJ42y3pW38qP+ntctiRszuauh+DAg4hiBBMRAgAiBQJa
      Vjd9AhsDBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRAcL8A7qSHayhBtAKCJ
      JikdIv0vXHb5/UQUGQk4yh2N+ACcCRCOC+bErjphevkYFcBFivDEcEi0KUV2Z2Vu
      eSBTaW5lbG5pa292IChCYXNlKSA8c2luQGJhc2VhbHQucnU+iGIEExECACIFAlpW
      N8oCGwMGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJEBwvwDupIdrKZAsAnivT
      gvtMOtRx4JdR7t7TuQrCHSFTAKDAIySZ3fL2cRKM2XeP0ZzbVacjFLkCDQQ/tMNG
      EAgAwxGwUaxQCJknES0PmVZxn/C6mxm0m1Nv1Fi/H+kJATthwrlYnH8AqRStDnKP
      2AgoryLGVGqguCjQExmu4wlTs/FA71JIHwel4FImUqSu4Ar0GJmZpCZF9HuBgSkK
      RUHzl2DdTDfhb424xhhFDsbDJGer4Rgp/RT9wriy7nBfGKvOjmy0srqQrqnwpbUY
      FVOiR1tV/umMdRG0UaL/rS7Y18ph7wx4smQiy3iC9WD6yldFt6iYWY9TcjS54Kqb
      KKjVYlf6sUYEBa0oZBOCaxtS+PIollWg+WYQrFZVNIMZXnLqwktSbGezhPMBAT7x
      GUp9fpDgt2e0GjeYiYmDsraobwADBQf/YGaQqxLOsLa9yl06sQblXrhL0GBFLizj
      zpGok9xEEVNqAPuza7J4f85x+u6zvcc9Quld1dGjSGMOVocX3J9wP1b/t9imKUkz
      MBDbZ2uJMo8tnADqcOMLgay/41usAr5UIV/wCyNA3DmQfzbAT3/YH92d01h36zXv
      eQtllxDy1g+Co8UIF7HmwLjL8tneX6RNfURGBTfOox9fkfFMRvqLCtq6a1kCgXD0
      u0h1Jkx3jXJB6fN+Z7mXsubyeyNAo0fH1Cw+eR4pOGCRbcYzIoS7LTvjBseAS4UW
      TqR87Qcy7OgH1RuHK1PcmnnQTtxvf4jm2Y7jL0uLubrqk5lO7nB33YhJBBgRAgAJ
      BQI/tMNGAhsMAAoJEBwvwDupIdrKM2sAoJTlTRchDKe/NgahXy+9WQ0EmMH7AKCz
      WE477AnCyyTPt9Dqv34trgxcSQ==
      =RofD
      -----END PGP PUBLIC KEY BLOCK-----

  gkot:
    ssh-key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICyM3gQAxEjxTp2R4JfmPgGOdS0cWVci0VOrRWqXGP8D gkot@altlinux.org"
    pgp-key: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----

      mQINBFomTS4BEADIFuSh9FB16c7PhfI1atG6WBpKVw60RMz+55mEyT1JKhXLfkPj
      2HHQJP3EP9B6r0SetbeBr3jSPUFqU5bd0PE2s0tlVqTAnXv1YgtCjnUJas0a2u8M
      niYnIlR67IBo8dipqGtcvGUevCMPPMe5TWvaF7xveoYG2u6JLZUaSM6YNjpqevcJ
      EqFALhbDHufdW7efpVwCmdbOyrGo9CH3jVAyWUrRD3eBpdKiqUx0T5Z2K615QuxS
      U7tOif5gz450t4qAZj88MuxCZObR07NMPLhgqyyC4KEHmv5v2KOrn7+kogOmgTpB
      5a8sY+qFoJvxiRet4vwxvZRG9hlkbAEbMANQbDFnKS83ufotiJ+/0ugGUHC4K4GF
      WI4HeZZfYEHy74dpvEyRiI7wENwKChEiO/Q5dTw4ovuHulUdgdN+MxP4VQJ6/IpP
      GhJOWsOXbGCX0gpV1x71PDVTJZIB/iWLSrTR2GJCwpO893KN3nt9qTRpgD/+od4F
      YNcxVhfdJSD/mbbC0qMSKqLKzSaxnIKahLREuQ7dt1zRmgZ5Z0wOHff4/EPq2Fgv
      +EXhCY/mnuqqZwdD1CXKyXHqLb0gppRVpUTMuyc3r5dSIHH05DLc1x4afqdQVamR
      wa2cKPkX73BnIAG5fUgU77Jk7AJ+xORXh2TsluCS5CvD2hsGs3w/5u84awARAQAB
      tCZHZW9yZ3kgQSBCeXN0cmVuaW4gPGdrb3RAYWx0bGludXgub3JnPokCOAQTAQIA
      IgUCWiZNLgIbAwYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQej5+lyHE1MtB
      YxAAwoxJX1r8RMRRrMMZPAHRL6jQoWr1rw04uyoBKJwlhpy3r0wyOWKvlhe56NDV
      Hf5Cozb2pximqytqQIfTHwQMjqixWnxYMfTyKyrU3h0o5sFmarShJJ5m85sOhqzb
      Fr2SmzW81icrxzvH2PlIkX/A0+iljjbnkxANmTdApNUx1+Qw5lKisiL0EI81IDH5
      VO7wFMp8Yn5FEos27oF2cyA/7rYPXOLXCMSGjDSfDaiH8ofXvMH3BaJBy9nIY9Oc
      9Fffek7enoLDoJW/6vC6ZkQTae6BW+ELvWkPEwgW3mkYjTZ4aoCXS3UBVLaDqEAQ
      5Zv1p6xNkb+T53NyQYwLvHftWaUviLEnshzatOAwLNqWhIoP7WH3DqNdUu/I5jKD
      FPfsWxZB6cxald5Zng21MjPi7/iwGfMKvS3xZXARoCyli6JQxT5jVqW1Bf65qE0w
      P27a6lMgZoNY8ccYL5iABgz/BvRqPXlf3p3hDb2g6gq5BDmjc1RW0dZmA9MMAqzw
      LOuR4ir2HgU7PkhLWPT5u3x8H+UYhUu9YZtAJvPmLStZAbXizer9vY0cBG4Xp6yA
      93q8aB5VNW/DX4rKoR6Wkn5+OHHgxV1UGVHafyApZplrUIOQ+Gkfh9zSahBx2w57
      Dgnl8S2/bss4L8iQPk93m8kSo3/DVLRmxWpLoEKfIOnVcf65Ag0EWiZNLgEQAMEp
      p71/UyJ36xzaqXZn2BGogGnOiX1mjYhIY1cpLvDoL4EtJeH+fy/bnwuPqiBc1Njb
      TR+6xsaGzxXJgFXcVcXnZdHZnRbrrodqSsXvsOLjNGAQCyUwsaN5trAN6e+i/Wx9
      /fnFtgdGMS3meGMVgW3o9sCSboKt1LzVPrhHkhiXr+uXqInbMqbP44qWyEP+yzKn
      +WU3TK9z3kCgxywDlGT77ZMg2MGbAuutQdWPJLWg8cmM1tIUQ3LQlcM5by2HO8uZ
      S5QAE4ZhseP23lMlL4kWqDlGqEVP+c11AQfxzHdKnaEfYeeSjdY+V3IyfLQ+gyex
      k9s8Mt8CN/YGkWc3Mt4rfmkZAPvHLNwGp9VmMAIj2RenZie/OEx8Bul+dCvKR+XM
      qzW5RLvWrzJSIvkEv811ndvjrGZEvLcX3l6VZE5ksa6ryfX6QvhgnRscFE1WuWfn
      A+5cIANCC7GAaMNqrxrso4T5jjnOTEDYg+MuGSist9ZecMwLY5PWUtrxd8b/1ZDG
      NO5KLwkrbI/8oB4C/mL4fg7sbNaP1omrOveKynFmKRnpK60iAReyv6F4G858OZF0
      B7I6OAXTsluyc4LoSI45kD5gI30QQY+Af/75kbwMDsQZhLd6QlPpajnaJ0Kx0hoP
      EFMZ1uQHNAu6PRlD9mMuqzHoDXgUAxUz0dpHqP7lABEBAAGJAh8EGAECAAkFAlom
      TS4CGwwACgkQej5+lyHE1Mt8UA/+ITxagTts3VpewcMfWkrWowswRbrPZzxkMXIF
      Kvm/NbFMkBkMbzKxKe12DGTFPN/HqRO6cIr9I9ioc20Jf8KkXuz7qe06fJ0qo9zd
      X0N97UHmwx5jVupSUhqU+qYwNeLj/Q2Sk5PvxAnNj0qNK9g3KB3LfGZHBWeknAKX
      mDBJaEduAYEb/HnsM9uOCAD+Ab7j+GgC5pFuIkAQytIdYwaufUZsJ9X1nWbTR8k4
      jC3IZF7MHJOmVhLx/lwx+gWduCqE6kNM/+fbYVLfZWHS85VZ+5Qm4ZS/FS9CQ2JE
      BD6PXvF8DP5Sh/jFYLfdje0IKdyP7/4a6MyIVZg2rj3n3YWZHqdgiiXwasRbgIDb
      dmlleJ4+OveAnMMjgzwVkTmX13HmTrZZSwaGmpCrVVDBZeRH2WKBo/jy7cmVDwnh
      o2q3Trh4SFFtH9lsKFQw7qZn22ANjfu+fRRDiSTX987u/UALLYyFIgGUhIFD1BOB
      gCMOTB8KvxJWnnUTKRlL/GyGKMgCeSPDCUtBow0p4ReZeK9hxpPNxrFcCKMDQv21
      qr+5E/D0XHYY9Uf7VGKGHWYMvJC5r7lZsaM9MAkk1EEQ1U22G5YHUL/rHFVTL9eo
      16J/zWS2RwAlXg4MQYcAzMnDP1Vh1wIukmu6JBGBnpfd6BtPY6Ln2CJeM738OEtU
      tN7kJWE=
      =lPjA
      -----END PGP PUBLIC KEY BLOCK-----

  jqt4:
    ssh-key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA7ccoKFFO2fa+KgKMi6HbRr9SmdWvZAkfqqdK1fw1hf altlinux@localhost.localdomain"
    pgp-key: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----

      mQINBFqsGrQBEAChI7xqxUCkWpE7lms0cDBipYpadIHKHF1utRr4mN07w6re1VLK
      r9h38a1X9H7RMiJlWw2Tv5VTI0kY86f0Lqr4HovU1pMoxongTWOMHZIK6Dh8K/CX
      EHZkPSiQdWv369Lx9HKc9XerjeLkpErBKbbcFNQi1ML7H1YBGERKqZbnotRzlmN+
      jXVYyZN6dY4oq3BNmaDbVQrEpDjoQBHZlbpoA8qySVeTDZ6xAwIIVXI0LCguLHF2
      rRXjAmuWdZI410iqtPBKvCX1ROpSd6WkxXHDzKU1V4yWjwT2apuyWUmWqlugYyjk
      WdxXWQEx5s/TBp1OXDetIbjxZ2d4nvaPpDGORx8JVdSVXpaX2YS+sSbRnxDLMPvk
      DSA4e5NH8WlSRKCGFV2+o+D/vJ+03uKkwN6OePRgL5qGsdqETgrxo0pnvOQf9X9s
      fiiv86FrMCdOr8jgHSCeJRUuvQIFucJpihIJUF1eNrTnGLAMQQppZ6fIlezwlXsU
      GGno0rRubKOmsP3/fI0WTcZAh07haRNzRjNgqp/hxQFplPzRosXldRXXlqtkN5B1
      CCtRTbn2LeAUc7yM1FOgkpaym2aACPtfSNnmXGsPfdB7n6/l5QqcKZRQcdBgatFG
      NU61S/CjjkFA0u7Jge87R4H1qz1Z+FixSjQ39BLf/meEbTQIV533Qce+xQARAQAB
      tCREbWl0cml5IFRlcmVraGluIDxqcXQ0QGFsdGxpbnV4Lm9yZz6JAjgEEwECACIF
      AlqsGrQCGwMGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJED9hs0Z/7SvBmH0P
      /ikfvt9lL+iSTkdMJ+4SoDkrrWU3Ul5zbgBXHxBOMcYTspBIIoWfGIe7M4LK9DUd
      50E24exYSdXUpPZFgJNzA7TfhEM0ijnorv8jwoqOw7+1BVXDwflS3ECiVFAy14PB
      QL2W14Q0WZKiYrR/gCwduo0WDB+G4YZquQnCDFHtQJAqYBiKbznKaGNqOUhTLFSE
      SQqcFRpYBKsHgQKIaJedDJjHZ3eOY+uw3bbF+z08vvSKqNLFITJ1DeqNqUW8hOqb
      d4y0KrI+PbPc7Xil0Ea47oh6VExbHpsfIA2NA4V7qtJNukMLVh7sJTyCEBoWHMkG
      Vcsm6+Obd18FaFwKiEeXJNXq3hhthi+DL8nEBKHeHtRNbqPnurV7Z4WueQs4Ezn+
      FMjtFLcGH92VIxa/OoIpkCEMZcdwwWCetqZvQ1x9Lklhnw6YEnwVp4T0w0ezdgh3
      qXttMAVUmLVdXI28spl7oZsLKx3w0Do5o9U7auPNocTlbqqaV7W/R/CsqJhEmyLu
      okKqXkMd41KAXegb1V473lmAsjkKQW1ycnWj92qmoh2HRGwh0M1mcr44NjmjAxX4
      hgCbOdXq0LIHtcJ/tJpcnOdaDeEU7j45OUZv8m3vVjzZz6j+WiHSeMyobWpxlkrR
      DSCJvgx8ZUbI06aM/A8Gdvsjo8IGNmIaF3HNX9+Ej6GsuQINBFqsGrQBEADeijNz
      MOMs1M/MCioqnrZfnPDFHJCr6kAXUWpDze2rO1yjlXxCrWkWacts1mEDi4ugua8X
      /Gi88GZqjfNKrDbuSoV7Tix/4uNdzdBcbd5GFZyy4CJCGtI9ToaZ4tRbzxhMo47p
      w8ivOGOYh30WkOLfnj1cSEzV5pZZtl9SuLZNNHDHENZS1alexDntdxMDkb3w2wYZ
      Jx1sBUWe9BhTbgyGjCX9zeM/aTNkVJGizRJZqEvuXyC1SpiVy3bP3QEWc+Nh7p3u
      5b8uIvL1B5pwQ8goOqLYO84P0zQ8W6CQaskcURmJyQFrTtWwNLOPfaYK4XzQnLWj
      Fr6E79OybByUiwEJC77QpHmuT3a5hSbffh4uodLU2Gr93hdLEG6/XNvn/VHSVbkk
      L7d+nfMz8jE0sTHrJ1BamqgnWzlput1nCo1jOxttHXA0lAZrgw8U/XK4bRCtPg2P
      X2bdpjN1yz4FV/hGpgcjxPtCEt/mHo+b9WR3wA2toeDp0/XXzu6p7+lUqmWUuYtU
      sBxGCj5OJNNteKm9BmCseLpw4kbjxGeMpbcNf688/80bRHmcmUN6bKUwwIPqIldu
      ww4wItIXOjjwCcECAFpNq58Lq/D1gvsem58OkTaik0b9ZlfstDIM7STV+cSi6C3f
      nV77fSVYwdCrBarYSZ8fSRu0JbUC1Y8cEoFeKQARAQABiQIfBBgBAgAJBQJarBq0
      AhsMAAoJED9hs0Z/7SvBZOgP/0uSAvoKSOBJFwhgI09J2GWi0/wT5mbJ6cyhEg2Z
      Mya2ps56XP2n7blt5r3kraQ0BfYt3a5+w1+jgsfw/SBjEBbheWB/cuFoFZx4EAL2
      pgKxS9KDCuGhjeqUS1DK0BEXFMzjejQErBFHIsfP89P0gkGq7hgB7XxRJL1F3z1C
      8T14qcp7+4cOcxzSDajCboCdtbvmIOeetpIzhmePFUiRPjBpbEPtBK77cUzgOjnj
      AAqgwZMfRKPGUtmdkXzakSwM4vq/kMNzEtxUXPJ0RcDouUEkaS8Nz1dvfswIKyl7
      1srFT6D7I2TUwNkfNFcyVwbDAhC+Dv55r2vScWZKhycv1OnFCrbxEhMmCrz2Etls
      wKh/AFRnlgn7oPGkgJPyLU3vlAotzpkzPdEgq8jF7pFsRPj1y+BeBzrnr6FUoR5Y
      b3AnzE+OFN9NlEzWJqxZudIDAX0/oiQ4y5pRXxV/hfgjfqn0mTc9IKOHgTIO9V6B
      UQJM87n5RKE3y79UoIps6FWn/7qWX6VsD/XWWX8xhbl8JM/1w7cKw59kmoRBMDGq
      rTg5f47BrR5s5wH8VdZPD5TixYXc+7kg8dVuxLTF8P6XMKmoMouwhEm92LmFXZPU
      Xg2sOqnlqkaakwFOHasLjYczMwViQDGIWEhINZevPDdf7RdygWooe5zuDKJ/4n0T
      uR7T
      =V/D6
      -----END PGP PUBLIC KEY BLOCK-----
