---
galaxy_info:
  author: Bert Van Vreckem
  description: Sets up ISC BIND on RHEL/CentOS 6/7 or Ubuntu 16.04 LTS (Xenial) as an authoritative DNS server for a single domain (master and/or slave).
  license: BSD
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Ubuntu
      versions:
        - xenial
  galaxy_tags:
    - networking
    - system
    - dns
dependencies: []
